version: "3.9"

services:
  java-test:
    build: .
    container_name: java-test
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5005:5005"
    tty: true
    command: tail -f /dev/null